swagger: "2.0"
info:
  version: "0.0.1"
  title: Hello World App
# during dev, should point to your local machine
host: localhost:10010
# basePath prefixes all resource paths 
basePath: /
# 
schemes:
  # tip: remove http to make production-grade
  - http
  - https
# format of bodies a client can send (Content-Type)
consumes:
  - application/json
  - multipart/form-data
  - application/x-www-form-urlencoded
  - application/octet-stream
  - application/javascript
# format of the responses to the client (Accepts)
produces:
  - application/json

securityDefinitions:
  allowOnlySA:
    name: Authorization
    type: apiKey
    in: header
paths:
  /store:
    # binds a127 app logic to a route
    x-swagger-router-controller: stores.controller
    post:
      description: create a new store
      # used as the method name of the controller
      operationId: createStore
      parameters:
        - in: body
          name: body
          description: new store details.
          required: true
          schema:
            $ref: "#/definitions/StoreRequest"
      responses:
        "201":
          description: Success creation
          schema:
            # a pointer to a definition
            type: object
        # responses may fall through to errors
        default:
          description: Error
          schema:
            $ref: "#/definitions/Error"
  /swagger:
    x-swagger-pipe: swagger_raw
# complex objects have schema definitions
definitions:
  StoreRequest:
    required:
      - storeName
    properties:
      storeName:
        type: string
  Error:
    required:
      - message
    properties:
      message:
        type: string
